# Generated by Django 5.1.3 on 2025-05-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#e5e7eb', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icone',
            field=models.CharField(blank=True, help_text='Classe do ícone ou emoji', max_length=100),
        ),
    ]
