# Generated by Django 5.1.3 on 2025-05-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categoria_slug_categoria_cor_categoria_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='cor',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icones/categorias/'),
        ),
    ]
