# Generated by Django 5.1.3 on 2025-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_remove_categoria_cor_alter_categoria_icone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição'),
        ),
    ]
