# Generated by Django 5.0.4 on 2025-06-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_alter_categoria_options_categoria_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
