# Generated by Django 5.1.3 on 2025-06-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_categoria_slug'),
        ('categorias', '0006_alter_categoria_slug'),
    ]

    operations = [
    ]
