# Generated by Django 5.1.3 on 2025-06-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_merge_0005_categoria_slug_0006_alter_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
