# Generated by Django 5.1.3 on 2025-05-21 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_initial'),
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anuncio',
            new_name='Anuncios',
        ),
    ]
