# Generated by Django 5.1.3 on 2025-05-27 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_remove_anuncios_imagens_imagemanuncios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemanuncios',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='anuncios.anuncios'),
        ),
    ]
